# Machine Learning Zoom Camp Intro 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Q1
np.__version__

'2.0.1'

In [3]:
# Q2
pd.__version__

'2.3.1'

In [5]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [9]:
df.shape[0]

10000

In [12]:

df['fuel_type'].nunique()

3

In [16]:
df.isnull().any().sum()

np.int64(2)

In [ ]:
df[df['origin'] == []'ASIA']['fuel_efficiency_mpg'].max()

In [ ]:
# Q5

# after fi

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [47]:
# Q5
# the mean didn't change
mean_hp_after = df_2015["Engine HP"].mean() 

df_2015["Engine HP"].isna().sum()

0

In [48]:
print(round(mean_hp_before))
print(round(mean_hp_after))

273
273

In [51]:
# Q6

df_RR = df[ df['Make'] == 'Rolls-Royce']
df_RR.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
2921,Rolls-Royce,Corniche,2001,premium unleaded (required),325.0,8.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Luxury",Large,Convertible,15,10,86,359990
3505,Rolls-Royce,Dawn,2016,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Large,Convertible,19,12,86,335000
5275,Rolls-Royce,Ghost Series II,2015,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury,Performance",Large,Sedan,21,13,86,286750
5276,Rolls-Royce,Ghost Series II,2015,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury,Performance",Large,Sedan,21,13,86,319400
5277,Rolls-Royce,Ghost Series II,2016,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury,Performance",Large,Sedan,21,13,86,295850

In [62]:
X = df_RR[['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates()
X

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [63]:
XT = X.T
XT

                  2921   3505   5275   5279   7443   7553   11448
Engine HP         325.0  563.0  563.0  563.0  322.0  453.0  624.0
Engine Cylinders    8.0   12.0   12.0   12.0   12.0   12.0   12.0
highway MPG        15.0   19.0   21.0   20.0   15.0   19.0   21.0

In [67]:
X.shape

(7, 3)

In [68]:
XT.shape

(3, 7)

In [92]:
XTX = np.dot(XT , X)
XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv, XTX_inv.sum()

# sum of inv XTX is = 0.0322

(array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
        [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
        [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]]),
 0.032212320677486195)

In [94]:
# Q7
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
w = np.dot(np.dot(XTX_inv,XT),y)
w
# first element is = 0.1998

array([ 0.19989598, 31.02612262, 31.65378877])